[mypy]
python_version = 3.11
mypy_path = .
namespace_packages = True
explicit_package_bases = True
ignore_missing_imports = False

[mypy-celery.*]
ignore_missing_imports = True

[mypy-cugraph.*]
ignore_missing_imports = True

[mypy-networkx.*]
ignore_missing_imports = True

[mypy-ray.*]
ignore_missing_imports = True

[mypy-tiktoken.*]
ignore_missing_imports = True

[mypy-tree_sitter.*]
ignore_missing_imports = True

[mypy-sqlglot.*]
ignore_missing_imports = True

[mypy-jsonlines.*]
ignore_missing_imports = True
