"""
Aletheia ACS Engine (v5.1) - Advanced Cognitive Security & Governance
---------------------------------------------------------------------
Production-ready Execution Governor. Integrates dynamic configuration bus,
True AST-level SAST analysis (Guardrail/Accelerator), NetworkX Topological 
Cycle Detection (Readiness), SHA256 handshakes, and cosine-similarity Sycophancy Detection.

Architectural Scope: This engine acts STRICTLY as the evaluation and penalty 
enforcer in a multi-step pipeline, validating outputs generated by upstream agents.
"""


import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))
import logging
import hashlib
import yaml
import ast
import re
import numpy as np
import networkx as nx
from pathlib import Path
from typing import Dict, Any, List, Optional

# --- Deterministic Seeding ---
import os
import random
os.environ["PYTHONHASHSEED"] = "42"
random.seed(42)
np.random.seed(42)

logger = logging.getLogger(__name__)

# Import strict constraint/trajectory schemas
try:
    from src.core.models import Constraint, Trajectory
except ImportError:
    Constraint = None
    Trajectory = None

# --- Sentinel Codes for Deterministic Routing ---
SENTINEL_FATAL_SECRET = "[ACS_FATAL_SECRET_LEAK]"
SENTINEL_FATAL_SYNTAX = "[ACS_FATAL_SYNTAX_ERROR]"
SENTINEL_FATAL_SCHEMA = "[ACS_FATAL_SCHEMA_ERROR]"
SENTINEL_FATAL_CRASH  = "[ACS_FATAL_GOVERNOR_CRASH]"
SENTINEL_ERR_MATH     = "[ACS_ERR_SYCOPHANCY_MATH]"
SENTINEL_ERR_TOPOLOGY = "[ACS_ERR_TOPOLOGY_CYCLE]"
SENTINEL_ERR_MISSING  = "[ACS_ERR_MISSING_REASONING]"
SENTINEL_WARN_SYCO    = "[ACS_WARN_SYCOPHANCY]"
SENTINEL_WARN_UNSAFE  = "[ACS_WARN_UNSAFE_IO]"
SENTINEL_WARN_NODOC   = "[ACS_WARN_DOCSTRING_MISSING]"
SENTINEL_WARN_NOTYPE  = "[ACS_WARN_TYPE_HINT_MISSING]"
SENTINEL_WARN_GAP     = "[ACS_WARN_EXPLANATORY_GAP]"
SENTINEL_WARN_DENSITY = "[ACS_WARN_LOW_DENSITY]"
SENTINEL_QUALITY_UNDERFLOW = "[ACS_QUALITY_UNDERFLOW]"

# Quality scoring constants
QUALITY_EPSILON = 0.1  # composite_quality_score underflow threshold
DEFAULT_SCALING_FACTOR = 1.0


class SycophancyDetector:
    """
    Sycophancy Detection Layer (Cosine-Similarity Model).
    Uses cosine similarity between the agent's response distribution and a
    uniform-conviction reference to detect alignment-faking / echo-chamber
    behavior. If the response skews too closely to the prompt's framing
    (low divergence from a sycophantic baseline), conviction drops.

    sensitivity is used as a Tikhonov regularization term (λ) to stabilize
    cosine similarity computation against near-zero-norm vectors.
    """
    def __init__(self, sensitivity: float = 0.15):
        self.sensitivity = sensitivity  # Tikhonov penalty (λ) for norm stabilization

    def compute_conviction(self, response_signals: List[float], baseline_signals: List[float]) -> float:
        """
        Cosine similarity between response signals and baseline reference.
        Returns conviction score in [0, 1]. Low conviction = sycophancy detected.
        
        response_signals: numeric features extracted from the agent's output
                          (e.g., [agreement_ratio, hedging_score, novelty_score])
        baseline_signals: reference distribution for a non-sycophantic response
        """
        try:
            resp = np.array(response_signals, dtype=float)
            base = np.array(baseline_signals, dtype=float)

            if np.isnan(resp).any() or np.isinf(resp).any() or np.isnan(base).any() or np.isinf(base).any():
                logger.error(f"{SENTINEL_ERR_MATH} Signal data contains NaN/Inf. Defaulting conviction=0.0.")
                return 0.0

            if resp.size == 0 or base.size == 0:
                return 1.0  # No signals = cannot detect sycophancy, assume conviction

            resp_norm = max(float(np.linalg.norm(resp)), self.sensitivity)
            base_norm = max(float(np.linalg.norm(base)), self.sensitivity)
            # Tikhonov floor guarantees non-zero denominators

            similarity = float(np.dot(resp, base) / (resp_norm * base_norm))
            # High similarity to baseline = high conviction (non-sycophantic)
            # Low similarity = the output diverges from expected honest response
            conviction = max(0.0, min(1.0, similarity))
            return conviction
        except Exception as e:
            logger.error(f"{SENTINEL_ERR_MATH} Conviction computation failed: {e}")
            return 0.0

    def compute_cosine_slr(self, signal_a: List[float], signal_b: List[float]) -> float:
        """
        Compute cosine-distance SLR (Sycophancy Likelihood Ratio) between two signal vectors.
        Returns cosine distance (1 - cos_sim) in [0, 1].
        0 = identical orientation (no sycophancy risk), 1 = orthogonal (max risk).

        Uses self.sensitivity as Tikhonov regularization (λ) added to norms
        to prevent instability on near-zero vectors.
        """
        try:
            a = np.array(signal_a, dtype=float)
            b = np.array(signal_b, dtype=float)
            if a.size == 0 or b.size == 0:
                return 0.0
            if np.isnan(a).any() or np.isnan(b).any():
                return 0.0
            a_norm = max(float(np.linalg.norm(a)), self.sensitivity)
            b_norm = max(float(np.linalg.norm(b)), self.sensitivity)
            cos_sim = float(np.dot(a, b) / (a_norm * b_norm))
            return round(1.0 - max(0.0, min(1.0, cos_sim)), 4)
        except Exception as e:
            logger.error(f"{SENTINEL_ERR_MATH} Cosine SLR computation failed: {e}")
            return 0.0

    def compute_tikhonov_slr(self, confusion_matrix, response_vector) -> float:
        """
        Full Tikhonov Ridge Regression SLR (D2+D12).
        Computes w = (A^T A + αI)^{-1} A^T y where α = self.sensitivity.
        Returns cosine distance between w and y as the SLR in [0, 1].
        Primary path when confusion_matrix is a proper 2D signal matrix.
        """
        try:
            A = np.array(confusion_matrix, dtype=float)
            y = np.array(response_vector, dtype=float)
            if A.ndim != 2 or A.size == 0 or y.size == 0:
                return 0.0
            if np.isnan(A).any() or np.isnan(y).any():
                return 0.0
            n_cols = A.shape[1]
            # Ridge regression: w = (A^T A + α I)^{-1} A^T y
            AtA = A.T @ A + self.sensitivity * np.eye(n_cols)
            Aty = A.T @ y
            w = np.linalg.solve(AtA, Aty)
            # SLR = cosine distance between w and y (pad/truncate to match)
            w_len = len(w)
            y_len = len(y)
            if w_len < y_len:
                w = np.concatenate([w, np.zeros(y_len - w_len)])
            elif y_len < w_len:
                y = np.concatenate([y, np.zeros(w_len - y_len)])
            w_norm = max(float(np.linalg.norm(w)), self.sensitivity)
            y_norm = max(float(np.linalg.norm(y)), self.sensitivity)
            cos_sim = float(np.dot(w, y) / (w_norm * y_norm))
            slr = 1.0 - max(0.0, min(1.0, cos_sim))
            return round(slr, 4)
        except np.linalg.LinAlgError:
            # Singular matrix — fall back to cosine SLR with flattened signals
            logger.warning(f"{SENTINEL_ERR_MATH} Tikhonov solve failed (singular), falling back to cosine SLR.")
            flat_a = np.array(confusion_matrix, dtype=float).flatten().tolist()
            flat_y = list(response_vector)
            return self.compute_cosine_slr(flat_a, flat_y)
        except Exception as e:
            logger.error(f"{SENTINEL_ERR_MATH} Tikhonov SLR computation failed: {e}")
            return 0.0

    def compute_slr(self, confusion_matrix=None, response_vector=None,
                    signal_a=None, signal_b=None) -> float:
        """
        Unified SLR dispatch. Prefers Tikhonov Ridge Regression when a 2D
        confusion_matrix is available; falls back to cosine SLR otherwise.
        """
        if confusion_matrix is not None and response_vector is not None:
            arr = np.array(confusion_matrix, dtype=float) if not isinstance(confusion_matrix, np.ndarray) else confusion_matrix
            if arr.ndim == 2 and arr.size > 0:
                return self.compute_tikhonov_slr(confusion_matrix, response_vector)
        if signal_a is not None and signal_b is not None:
            return self.compute_cosine_slr(signal_a, signal_b)
        return 0.0

    # Backward-compatible alias
    compute_vector_slr = compute_cosine_slr


class ACSExecutionGovernor:
    """
    ACS v5.1: Context-Aware Governor.
    Applies polymorphic SAST, Generative Utility, and Readiness penalties,
    secured by a SHA256 handshake and dynamically tuned via the Config Bus.
    Fully compatible with strict Pydantic models (AletheiaSkill).
    """
    def __init__(self, config_path: str = "config/engine_config.yaml", telemetry=None):
        # 1. Dynamic Config Bus Integration
        self.config = self._load_dynamic_config(config_path)
        self.telemetry = telemetry
        
        acs_cfg = self.config.get("acs_tuning", {})
        self.strictness = acs_cfg.get("strictness", 0.80)
        self.penalties = acs_cfg.get("penalties", {
            "syntax_error_mult": 0.50,
            "unsafe_io_mult": 0.70,
            "sast_finding_mult": 0.85,
            "sycophancy_mult": 0.40,
            "utility_cosmetic_mult": 0.95,
            "circular_logic_mult": 0.50
        })
        
        # Initialize the Sycophancy Detector with dynamic sensitivity
        syc_sensitivity = acs_cfg.get("sycophancy_sensitivity", 0.15)
        self.sycophancy_detector = SycophancyDetector(sensitivity=syc_sensitivity)
        
        # High-entropy / Secret Regex patterns (Replacement for gitleaks)
        self.secret_patterns = [
            re.compile(r"(?i)api[_-]?key[\s:=]+['\"][a-zA-Z0-9_\-]{16,}['\"]"),
            re.compile(r"(?i)aws[_-]?access[_-]?key[\s:=]+['\"][A-Z0-9]{20}['\"]"),
            re.compile(r"(?i)password[\s:=]+['\"][^'\"]{8,}['\"]"),
            re.compile(r"(?i)secret[\s:=]+['\"][a-zA-Z0-9_\-]{16,}['\"]"),
            re.compile(r"sk-[a-zA-Z0-9]{48}") # OpenAI key signature
        ]

    def _load_dynamic_config(self, config_path: str) -> Dict[str, Any]:
        """Safely loads parameters from the centralized YAML bus."""
        path = Path(config_path)
        if path.exists():
            try:
                with open(path, "r", encoding="utf-8") as f:
                    return yaml.safe_load(f) or {}
            except Exception as e:
                logger.warning(f"[!] ACS Engine failed to load config bus: {e}")
        return {}

    def _apply_penalty(self, current_score: float, multiplier: float, floor: float = 0.2) -> float:
        """Applies a multiplicative penalty bounded by an absolute epistemic floor."""
        if current_score > floor:
            return max(current_score * multiplier, floor)
        return current_score * multiplier

    @staticmethod
    def _make_constraint(ctype: str, description: str, severity: str = "warning", tags: Optional[List[Any]] = None, valid: bool = False):
        """Creates a Constraint object if the schema is available, else returns None."""
        if Constraint is None:
            return None
        return Constraint(type=ctype, description=description, severity=severity, tags=tags or [], valid=valid)
        
    def _scan_for_secrets(self, text_content: str, violations: List[str]) -> bool:
        """Lightweight regex-based secret scanner (replaces subprocess gitleaks)."""
        if not text_content:
            return False
            
        for pattern in self.secret_patterns:
            if pattern.search(text_content):
                msg = f"{SENTINEL_FATAL_SECRET} Hardcoded secret/key detected"
                violations.append(msg)
                logger.critical(msg)
                return True
        return False

    def _evaluate_pipeline_fidelity(self, text_content: str, violations: List[str]) -> float:
        """Validates YAML pipeline structure (Structural Integrity)."""
        penalty_mult = 1.0
        try:
            pipeline = yaml.safe_load(text_content)
            if not isinstance(pipeline, dict) or "steps" not in pipeline:
                msg = f"{SENTINEL_FATAL_SCHEMA} Missing mandatory 'steps' array in YAML"
                violations.append(msg)
                logger.error(msg)
                return self.penalties["syntax_error_mult"]
                
            for step in pipeline.get("steps", []):
                if not isinstance(step, dict) or not all(k in step for k in ("name", "action")):
                    msg = f"{SENTINEL_FATAL_SCHEMA} Step missing mandatory 'name' or 'action' key"
                    violations.append(msg)
                    logger.error(msg)
                    penalty_mult = min(penalty_mult, self.penalties["syntax_error_mult"])
        except yaml.YAMLError as e:
            msg = f"{SENTINEL_FATAL_SYNTAX} YAML parsing error - {str(e)}"
            violations.append(msg)
            logger.critical(msg)
            penalty_mult = min(penalty_mult, self.penalties["syntax_error_mult"])
            
        return penalty_mult

    def _evaluate_sast_fidelity(self, text_content: str, sast_findings: List[Any], violations: List[str]) -> float:
        """
        True AST SAST Parsing (The Guardrail & Accelerator Functions).
        Moves beyond string matching to robustly identify logical anti-patterns,
        unsafe I/O operations, and generative utility (docstring presence).
        """
        penalty_mult = 1.0
        
        if text_content:
            # Hardening: Prevent AST memory exhaustion attacks
            if len(text_content) > 1_000_000:
                msg = f"{SENTINEL_FATAL_SYNTAX} Artifact exceeds maximum safe AST parsing size (1MB)"
                violations.append(msg)
                logger.critical(msg)
                return self.penalties["syntax_error_mult"]

            try:
                tree = ast.parse(text_content)
                
                # 1. Guardrail Function: Axiomatic Alignment & Unsafe Calls
                unsafe_funcs = {"eval", "exec", "system", "Popen", "__import__"}
                for node in ast.walk(tree):
                    if isinstance(node, ast.Call):
                        func_name = ""
                        if isinstance(node.func, ast.Name):
                            func_name = node.func.id
                        elif isinstance(node.func, ast.Attribute):
                            func_name = node.func.attr
                        
                        if func_name in unsafe_funcs:
                            msg = f"{SENTINEL_WARN_UNSAFE} Unsafe AST Call '{func_name}' detected"
                            violations.append(msg)
                            logger.warning(msg)
                            penalty_mult = min(penalty_mult, self.penalties["unsafe_io_mult"])
                            
                # 2. Accelerator Function: Generative Utility Enforcement
                for node in ast.walk(tree):
                    if isinstance(node, (ast.FunctionDef, ast.ClassDef, ast.AsyncFunctionDef)):
                        if not ast.get_docstring(node):
                            msg = f"{SENTINEL_WARN_NODOC} Missing docstring in '{node.name}'"
                            violations.append(msg)
                            penalty_mult = min(penalty_mult, self.penalties["utility_cosmetic_mult"])
                            
                        # V4.2 Type-Hint Restoration
                        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                            is_init = (node.name == "__init__")
                            has_arg_hints = any(arg.annotation for arg in getattr(node.args, "args", []))
                            has_return_hint = getattr(node, "returns", None) is not None or is_init
                            
                            if not (has_arg_hints and has_return_hint):
                                msg = f"{SENTINEL_WARN_NOTYPE} Missing structural type hints in '{node.name}'"
                                violations.append(msg)
                                penalty_mult = min(penalty_mult, self.penalties["utility_cosmetic_mult"])

            except SyntaxError as e:
                msg = f"{SENTINEL_FATAL_SYNTAX} Syntax error in AST parsing - {str(e)}"
                violations.append(msg)
                logger.critical(msg)
                penalty_mult = min(penalty_mult, self.penalties["syntax_error_mult"])
        
        # Enterprise SAST Telemetry (From Semantic Slicer)
        if sast_findings:
            msg = f"{SENTINEL_WARN_UNSAFE} {len(sast_findings)} upstream SAST vulnerabilities detected"
            violations.append(msg)
            logger.warning(msg)
            penalty_mult = min(penalty_mult, self.penalties["sast_finding_mult"])
            
        return penalty_mult

    def _evaluate_topology_readiness(self, edge_hints: List[Dict], violations: List[str]) -> float:
        """
        Readiness Function (Operational Potential).
        Hunts for topological cycle defects (hallucination loops) using NetworkX.
        """
        if not edge_hints:
            return 1.0
            
        try:
            G = nx.DiGraph()
            for edge in edge_hints:
                src = edge.get("source") if isinstance(edge, dict) else getattr(edge, "source", None)
                tgt = edge.get("target") if isinstance(edge, dict) else getattr(edge, "target", None)
                if src and tgt:
                    G.add_edge(src, tgt)
            
            # Hardening: nx.find_cycle is O(V+E) and stops on first match, 
            # whereas list(nx.simple_cycles) is O((V+E)*C) and can hang on dense graphs.
            try:
                cycle = nx.find_cycle(G, orientation="original")
                msg = f"{SENTINEL_ERR_TOPOLOGY} Circular dependency defect detected {cycle}"
                violations.append(msg)
                logger.error(msg)
                return self.penalties.get("circular_logic_mult", 0.5)
            except nx.NetworkXNoCycle:
                pass # Graph is a valid DAG
                
        except Exception as e:
            logger.error(f"{SENTINEL_ERR_TOPOLOGY} Topology evaluation crashed: {e}")
            
        return 1.0

    def compute_sie_score(self, node: Any) -> Dict[str, Any]:
        """
        Computes Semantic Information Evolution (SIE) metrics for a node.
        Returns dict with content_density, alignment_vector, composite_quality_score, s_sie, and violations.
        
        content_density: derived from AST structural depth, docstring presence, type-hint ratio.
        alignment_vector: [coverage, novelty, consistency] 3-vector.
        composite_quality_score = mode_scaling_factor * content_density * ||alignment_vector||
        s_sie = composite_quality_score (same for now; mode_scaling_factor=1.0 default)
        """
        is_dict = isinstance(node, dict)
        def get_val(key, default=None):
            return node.get(key, default) if is_dict else getattr(node, key, default)

        violations = []
        text_content = get_val("code_snippet", "")
        
        # --- Compute content_density from AST complexity ---
        content_density = 0.0
        ast_depth = 0
        docstring_present = 0.0
        type_hint_ratio = 0.0
        func_count = 0
        hints_count = 0
        
        if text_content and text_content.strip():
            try:
                tree = ast.parse(text_content)
                
                # Measure AST depth via recursive walk
                def _max_depth(node_ast, depth=0):
                    max_d = depth
                    for child in ast.iter_child_nodes(node_ast):
                        max_d = max(max_d, _max_depth(child, depth + 1))
                    return max_d
                ast_depth = min(_max_depth(tree), 20)  # cap at 20 for normalization
                
                for n in ast.walk(tree):
                    if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                        if ast.get_docstring(n):
                            docstring_present = 1.0
                    if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)):
                        func_count += 1
                        has_arg_hints = any(arg.annotation for arg in getattr(n.args, "args", []))
                        has_return = getattr(n, "returns", None) is not None
                        if has_arg_hints or has_return:
                            hints_count += 1
                            
                type_hint_ratio = (hints_count / func_count) if func_count > 0 else 0.0
                
            except SyntaxError:
                # --- Text-based density fallback for non-code content (Theorist Mode) ---
                # Natural language from PDFs/documents cannot be AST-parsed.
                # Use word count + sentence structure as a proxy for content density.
                words = text_content.split()
                word_count = len(words)
                if word_count > 0:
                    # Heuristic: 50+ words = full text density (capped at 0.55 to not
                    # inflate above well-structured code). Presence of punctuation
                    # diversity (periods, commas, semicolons) signals structured prose.
                    punct_types = sum(1 for c in ".,:;!?()" if c in text_content)
                    punct_bonus = min(0.15, punct_types * 0.025)
                    ast_depth = 0  # no AST for text
                    content_density = min(0.55, (word_count / 50.0) * 0.4 + punct_bonus)

        if ast_depth > 0 or content_density == 0.0:
            # Only apply AST-based formula when we have AST data or no fallback triggered
            content_density = max(content_density, min(1.0, (ast_depth / 10.0 + docstring_present * 0.2 + type_hint_ratio * 0.3)))
        
        # --- Compute alignment_vector: [coverage, novelty, consistency] ---
        # Coverage: ratio of code that has assertions/test paths
        validation_data = get_val("validation", {}) or {}
        assertion_count = validation_data.get("assertion_count", 0) if isinstance(validation_data, dict) else getattr(validation_data, "assertion_count", 0)
        coverage = min(1.0, assertion_count / 5.0)  # 5+ assertions = full coverage score
        
        # Novelty: inverse of how common this skill_type/operator_type is (simple proxy)
        # Higher for uncommon types; default 0.5 for unknown
        skill_type = get_val("skill_type", "execution")
        novelty = 0.7 if skill_type in ("validation", "theoretical_reasoning") else 0.5
        
        # Consistency: reward having complete teaching_layer reasoning vectors
        teaching_layer = get_val("teaching_layer", {})
        reasoning = teaching_layer.get("reasoning_vectors", {}) if isinstance(teaching_layer, dict) else getattr(teaching_layer, "reasoning_vectors", {})
        if isinstance(reasoning, dict):
            filled = sum(1 for k in ["intent", "strategy", "constraints", "execution_pattern", "failure_modes"] if reasoning.get(k))
        else:
            filled = sum(1 for k in ["intent", "strategy", "constraints", "execution_pattern", "failure_modes"] if getattr(reasoning, k, None))
        consistency = filled / 5.0
        
        alignment_vector = [coverage, novelty, consistency]
        
        # --- Compute composite_quality_score and s_sie ---
        grad_norm = float(np.linalg.norm(alignment_vector))
        mode_scaling_factor = DEFAULT_SCALING_FACTOR
        composite_quality_score = mode_scaling_factor * content_density * grad_norm
        s_sie = composite_quality_score
        
        # Hard gate: underflow detection
        if composite_quality_score < QUALITY_EPSILON:
            msg = f"{SENTINEL_QUALITY_UNDERFLOW} composite_quality_score={composite_quality_score:.4f} < epsilon={QUALITY_EPSILON}. Node starved."
            violations.append(msg)
            logger.warning(msg)
        
        return {
            "content_density": round(content_density, 4),
            "alignment_vector": [round(v, 4) for v in alignment_vector],
            "composite_quality_score": round(composite_quality_score, 4),
            "mode_scaling_factor": mode_scaling_factor,
            "s_sie": round(s_sie, 4),
            "violations": violations,
        }

    def evaluate_node(self, node: Any) -> Any:
        """
        Main evaluation entrypoint called by DAGRuntime.
        Pydantic/Schema Conformance (Gatekeeper Function): Dynamically handles both 
        raw dictionaries and strict Pydantic objects (AletheiaSkill).
        """
        try:
            is_dict = isinstance(node, dict)
            
            def get_val(key, default=None):
                return node.get(key, default) if is_dict else getattr(node, key, default)

            # Extract Meta
            source_type = get_val("source_type", "ast_code")
            artifact_type = get_val("artifact_type", "python")
            text_content = get_val("code_snippet", "")
            node_id = str(get_val("node_id", "unknown"))
            skill_type = get_val("skill_type", "standard")
            
            # Safe Extraction of Nested Attributes
            entry = get_val("entry", {})
            sast_findings = (entry.get("sast_findings", []) if isinstance(entry, dict) else getattr(entry, "sast_findings", [])) or get_val("sast_findings", [])
            
            semantics = get_val("semantics", {})
            ops = "->".join(semantics.get("operator_types", []) if isinstance(semantics, dict) else getattr(semantics, "operator_types", []))

            # 1. Cryptographic Handshake (Lineage Integrity)
            material = f"{node_id}|{text_content}|{ops}".encode('utf-8')
            cryptographic_sid = hashlib.sha256(material).hexdigest()
            
            # Epistemic Score Extraction
            epistemic = get_val("epistemic", {})
            if is_dict:
                current_c_node = epistemic.get("c_node", 1.0)
                local_conf = epistemic.get("confidence", {}).get("local", 0.0)
            else:
                current_c_node = getattr(epistemic, "c_node", 1.0) if epistemic else 1.0
                local_conf = getattr(epistemic, "confidence", {}).get("local", 0.0) if hasattr(epistemic, "confidence") else 0.0
                
            violations: List[str] = []
            structured_constraints: List[Any] = []  # Typed Constraint objects for domain-driven audit trail
            
            # V5.1 Upgrade: Native Secret Scanning
            has_secrets = self._scan_for_secrets(text_content, violations)
            if has_secrets:
                c = self._make_constraint("operational", "Hardcoded secret/key detected", severity="fatal", tags=["secret", "security"])
                if c: structured_constraints.append(c)

            # 2. Cognitive Governance (Cosine Similarity Sycophancy Audit)
            trajectory_raw = get_val("reasoning_trajectory", {})
            # Attempt to parse into strict Trajectory schema
            trajectory_obj = None
            if trajectory_raw and Trajectory is not None:
                try:
                    if isinstance(trajectory_raw, dict):
                        trajectory_obj = Trajectory.model_validate(trajectory_raw)
                    elif hasattr(trajectory_raw, 'model_dump'):
                        trajectory_obj = trajectory_raw  # Already a Trajectory instance
                except Exception:
                    trajectory_obj = None  # Fall back to raw dict access

            # Extract response signals and baseline from typed Trajectory or raw dict
            response_signals = None
            baseline_signals = None
            if trajectory_obj is not None:
                response_signals = trajectory_obj.confusion_matrix
                baseline_signals = trajectory_obj.response_vector
            elif trajectory_raw:
                response_signals = trajectory_raw.get("confusion_matrix") if isinstance(trajectory_raw, dict) else getattr(trajectory_raw, "confusion_matrix", None)
                baseline_signals = trajectory_raw.get("response_vector") if isinstance(trajectory_raw, dict) else getattr(trajectory_raw, "response_vector", None)

            if response_signals and baseline_signals:
                # D2+D12: Tikhonov Ridge Regression SLR (primary when 2D matrix available)
                tikhonov_slr = self.sycophancy_detector.compute_slr(
                    confusion_matrix=response_signals,
                    response_vector=baseline_signals,
                )

                # Flatten matrix rows into a single signal vector if needed
                if response_signals and isinstance(response_signals[0], list):
                    # Temporal weighting: later trajectory steps carry more signal
                    n_rows = len(response_signals)
                    if n_rows > 1:
                        temporal_weights = [0.5 + 0.5 * (i / (n_rows - 1)) for i in range(n_rows)]
                        flat_signals = []
                        for i, row in enumerate(response_signals):
                            flat_signals.extend([val * temporal_weights[i] for val in row])
                        response_signals = flat_signals
                        if len(baseline_signals) == n_rows:
                            baseline_signals = [val * temporal_weights[i] for i, val in enumerate(baseline_signals)]
                    else:
                        response_signals = response_signals[0]  # Single row, flatten

                # Pad shorter vector to match lengths
                max_len = max(len(response_signals), len(baseline_signals))
                response_signals = list(response_signals) + [0.0] * (max_len - len(response_signals))
                baseline_signals = list(baseline_signals) + [0.0] * (max_len - len(baseline_signals))

                conviction = self.sycophancy_detector.compute_conviction(response_signals, baseline_signals)
                slr_threshold = self.config.get("acs_tuning", {}).get("slr_threshold", 0.65)

                # SLR telemetry: record every computation for governance observability
                slr_computed = round(1.0 - conviction, 4)
                if self.telemetry:
                    self.telemetry.record(
                        "slr", "slr_computed", node_id=node_id,
                        payload={"slr": slr_computed, "conviction": round(conviction, 4),
                                 "tikhonov_slr": round(tikhonov_slr, 4)},
                    )
                
                # Store conviction back into Trajectory object if available
                if trajectory_obj is not None:
                    trajectory_obj = trajectory_obj.model_copy(update={"final_conviction": round(conviction, 4)})
                
                if conviction < slr_threshold:
                    msg = f"{SENTINEL_WARN_SYCO} Sycophancy detected via cosine similarity (Conviction: {conviction:.3f})"
                    violations.append(msg)
                    c = self._make_constraint("epistemic", msg, severity="error", tags=["sycophancy", "cosine_similarity"])
                    if c: structured_constraints.append(c)
                    logger.warning(f"Node {node_id}: {msg}")
                    current_c_node = self._apply_penalty(current_c_node, self.penalties["sycophancy_mult"], floor=0.1)
                    
                    # Causal governance: attach mutation directive for DAG runtime
                    slr_value = 1.0 - conviction  # SLR = 1 - conviction (cosine distance proxy)
                    if is_dict:
                        node["_governance_directive"] = {
                            "action": "reroll",
                            "reason": "sycophancy_detected",
                            "slr": round(slr_value, 4),
                            "conviction": round(conviction, 4)
                        }
                    else:
                        setattr(node, "_governance_directive", {
                            "action": "reroll",
                            "reason": "sycophancy_detected", 
                            "slr": round(slr_value, 4),
                            "conviction": round(conviction, 4)
                        })
                else:
                    current_c_node = min(1.0, current_c_node * 1.05)

            # 3. Structural & Triad-Specific Audits
            if source_type in ["ocr_document", "theory", "theoretical_reasoning"]:
                # Theorist Path: Graph Density & Topological Circular Loop Detection
                val_data = get_val("validation", {})
                complexity = val_data.get("complexity", {}) if isinstance(val_data, dict) else getattr(val_data, "complexity", {})
                density = complexity.get("graph_density", 0.0) if isinstance(complexity, dict) else getattr(complexity, "graph_density", 0.0)
                
                if density is not None and density < 0.1:
                    msg = f"{SENTINEL_WARN_DENSITY} Insufficient graph density (< 0.10)"
                    violations.append(msg)
                    logger.warning(f"Node {node_id}: {msg}")
                    current_c_node = self._apply_penalty(current_c_node, 0.7, 0.2)
                    
                edge_hints = get_val("edge_hints", [])
                topo_mult = self._evaluate_topology_readiness(edge_hints, violations)
                if topo_mult < 1.0:
                    current_c_node = self._apply_penalty(current_c_node, topo_mult, 0.1)
                    
            else:
                # Code-DAG Path: True AST Parse, Vulnerability Scans, and Docstring utility
                if artifact_type == "yaml" or text_content.strip().startswith("steps:"):
                    sast_mult = self._evaluate_pipeline_fidelity(text_content, violations)
                else:
                    sast_mult = self._evaluate_sast_fidelity(text_content, sast_findings, violations)
                
                if sast_mult < 1.0:
                    current_c_node = self._apply_penalty(current_c_node, sast_mult, 0.4)

            # 3.5 Epistemic Completeness Firewall (Platinum Quality Gate)
            teaching_layer = get_val("teaching_layer", {})
            reasoning = teaching_layer.get("reasoning_vectors", {}) if isinstance(teaching_layer, dict) else getattr(teaching_layer, "reasoning_vectors", {})
            heuristics = teaching_layer.get("heuristics", {}) if isinstance(teaching_layer, dict) else getattr(teaching_layer, "heuristics", {})
            
            required_vectors = ["intent", "strategy"]
            missing_vectors = [vec for vec in required_vectors if not (reasoning.get(vec) if isinstance(reasoning, dict) else getattr(reasoning, vec, None))]
            
            # Explanatory Gap Check
            use_when = heuristics.get("use_when", []) if isinstance(heuristics, dict) else getattr(heuristics, "use_when", [])
            avoid_when = heuristics.get("avoid_when", []) if isinstance(heuristics, dict) else getattr(heuristics, "avoid_when", [])
            
            if not use_when and not avoid_when:
                msg = f"{SENTINEL_WARN_GAP} Method lacks heuristic triggers (use_when/avoid_when)"
                violations.append(msg)
                c = self._make_constraint("semantic", msg, severity="warning", tags=["explanatory_gap", "heuristics"])
                if c: structured_constraints.append(c)
                logger.warning(f"Node {node_id}: {msg}")
                current_c_node = self._apply_penalty(current_c_node, self.penalties["utility_cosmetic_mult"])

            if missing_vectors:
                msg = f"{SENTINEL_ERR_MISSING} Missing reasoning vectors {missing_vectors}"
                violations.append(msg)
                c = self._make_constraint("structural", msg, severity="error", tags=["reasoning_vectors", "completeness"])
                if c: structured_constraints.append(c)
                logger.error(f"Node {node_id}: {msg}. Triggering terminal rejection.")
                
            # 3.8 Validation Layer Positive Reinforcement
            val_data = get_val("validation", {})
            assertion_count = val_data.get("assertion_count", 0) if isinstance(val_data, dict) else getattr(val_data, "assertion_count", 0)
            boost_applied = False
            
            if skill_type == "validation" and assertion_count >= 3:
                local_conf = min(1.0, round(float(local_conf) * 1.1 + 0.05, 6))
                boost_applied = True

            # 4. Finalize and Seal Artifact
            final_c_node = round(current_c_node, 3)
            
            # V4.2 Terminal State Reinstatement
            is_terminal = (
                SENTINEL_FATAL_SYNTAX in "".join(violations) or 
                SENTINEL_FATAL_SCHEMA in "".join(violations) or 
                len(missing_vectors) > 0 or 
                has_secrets
            )
            final_state = "terminal" if is_terminal else (get_val("epistemic", {}).get("state", "audited") if is_dict else getattr(get_val("epistemic", {}), "state", "audited"))
            
            # Serialize structured constraints for attachment
            constraints_dump = [c.model_dump() for c in structured_constraints] if structured_constraints else []
            trajectory_dump = trajectory_obj.model_dump() if trajectory_obj else None

            if is_dict:
                node["acs_handshake_sid"] = cryptographic_sid
                if "epistemic" not in node: node["epistemic"] = {}
                node["epistemic"]["c_node"] = final_c_node
                node["epistemic"]["state"] = final_state
                if "confidence" not in node["epistemic"]: node["epistemic"]["confidence"] = {}
                node["epistemic"]["confidence"]["local"] = local_conf
                if boost_applied: node["epistemic"]["confidence"]["assertion_grade_boost"] = True
                node["acs_violations"] = violations
                node["acs_audited"] = True
                node["_acs_structured_constraints"] = constraints_dump
                if trajectory_dump:
                    node["_acs_trajectory"] = trajectory_dump
            else:
                setattr(node, "acs_handshake_sid", cryptographic_sid)
                if hasattr(node, "epistemic") and node.epistemic is not None:
                    setattr(node.epistemic, "c_node", final_c_node)
                    setattr(node.epistemic, "state", final_state)
                    if not hasattr(node.epistemic, "confidence"):
                        setattr(node.epistemic, "confidence", {})
                    if isinstance(node.epistemic.confidence, dict):
                        node.epistemic.confidence["local"] = local_conf
                        if boost_applied: node.epistemic.confidence["assertion_grade_boost"] = True
                setattr(node, "acs_violations", violations)
                setattr(node, "acs_audited", True)
                setattr(node, "_acs_structured_constraints", constraints_dump)
                if trajectory_dump:
                    setattr(node, "_acs_trajectory", trajectory_dump)

            return node
            
        except Exception as e:
            # Global Hardening Guard: Prevent isolated governor failures from crashing the DAG runtime
            logger.critical(f"{SENTINEL_FATAL_CRASH} Governor logic encountered unhandled exception: {e}")
            if isinstance(node, dict):
                node["acs_violations"] = [f"{SENTINEL_FATAL_CRASH} {str(e)}"]
                if "epistemic" not in node: node["epistemic"] = {}
                node["epistemic"]["state"] = "terminal"
                node["epistemic"]["c_node"] = 0.0
            else:
                setattr(node, "acs_violations", [f"{SENTINEL_FATAL_CRASH} {str(e)}"])
                if hasattr(node, "epistemic") and node.epistemic is not None:
                    setattr(node.epistemic, "state", "terminal")
                    setattr(node.epistemic, "c_node", 0.0)
            return node