"""
Aletheia Reroll Engine v2.0 (D7 — 2-Candidate Branching)
Handles REROLL state transitions by generating 2 candidate outputs,
selecting the best via semantic scoring, and capturing DPO traces.
"""

import hashlib
import json
import logging
from typing import Dict, Any, Optional, List

logger = logging.getLogger("Advocate.RerollEngine")

# Keys generated by execute() that must be cleared before re-execution per mode
_MODE_CLEARABLE_KEYS = {
    "theorist": ["chunk_text"],
    "coding_assistant": ["code_snippet", "name", "theory"],
    "advocate": ["theory_text", "implementation_code"],
    "veteran": ["traceback", "analysis_text", "diff", "resolved_code", "attempt_code"],
}


def _score_candidate(semantics: dict) -> float:
    """
    Score a reroll candidate based on content density.
    Higher score = more informative output. Used by select_best.
    """
    if not isinstance(semantics, dict):
        return 0.0
    score = 0.0
    for k, v in semantics.items():
        if k.startswith("_"):
            continue
        if isinstance(v, str) and len(v) > 0:
            score += min(1.0, len(v) / 100.0)
        elif isinstance(v, list) and len(v) > 0:
            score += 0.5
        elif isinstance(v, dict) and len(v) > 0:
            score += 0.3
    return round(score, 4)


class RerollEngine:
    """
    Manages the reroll lifecycle for nodes that failed contract validation
    or received a governance directive to retry.

    Usage (inside DAGRuntime.run loop):
        reroll_engine = RerollEngine()
        if node.epistemic.state == "REROLL":
            result = reroll_engine.reroll(node, dag_runtime)
            if result:
                dag_runtime.rejected_traces.append(result)
    """

    def __init__(self):
        self.reroll_count = 0
        self.branch_count: int = 2
        self._rejected_fingerprints: List[str] = []

    def inject_failure_context(
        self,
        node,
        reason: str,
        violation_details: Optional[str] = None,
    ) -> None:
        """
        Augment the node's semantics with failure metadata so the next
        execution pass can use it as corrective signal.
        """
        failure_ctx = {
            "previous_failure_reason": reason,
            "reroll_attempt": self.reroll_count + 1,
        }
        if violation_details:
            failure_ctx["violation_details"] = violation_details

        if not isinstance(node.semantics, dict):
            node.semantics = {}
        node.semantics["_reroll_context"] = failure_ctx

        # Track structural fingerprint of rejected output for diversity signal
        ops = node.semantics.get("operator_types", []) if isinstance(node.semantics, dict) else []
        fp = hashlib.md5(str(sorted(ops)).encode("utf-8")).hexdigest()
        self._rejected_fingerprints.append(fp)

    def _clear_generated_keys(self, node, mode: str) -> None:
        """Remove mode-specific generated keys so execute() regenerates them."""
        keys = _MODE_CLEARABLE_KEYS.get(mode, [])
        for k in keys:
            node.semantics.pop(k, None)
        # Also clear extracted_patterns so they regenerate
        node.semantics.pop("extracted_patterns", None)

    def reroll(
        self,
        node,
        dag_runtime,
        reason: str = "contract_violation",
        violation_details: Optional[str] = None,
    ) -> Optional[Dict[str, Any]]:
        """
        Execute a multi-candidate reroll cycle on a REROLL-state node.

        1. Snapshot the rejected output.
        2. Generate self.branch_count candidates via separate execute() invocations.
        3. Select the best candidate via _score_candidate.
        4. Apply the best candidate to the node.
        5. Return a rejected trace dict with DPO-compatible structure.

        The caller is responsible for:
        - Checking retry_budget > 0 and decrementing it BEFORE calling reroll().
        - Re-running contract validation on the new output after reroll().
        """
        if node.epistemic.state != "REROLL":
            logger.warning(f"reroll() called on node {node.node_id} in state {node.epistemic.state}, expected REROLL")
            return None

        self.reroll_count += 1

        # 1. Snapshot rejected output
        rejected_snapshot = json.loads(json.dumps(node.semantics))

        # 2. Generate self.branch_count candidates
        candidates = []
        for i in range(self.branch_count):
            # Reset node to VALIDATED with failure context
            node.epistemic.state = "VALIDATED"
            candidate_semantics = json.loads(json.dumps(node.semantics))
            self.inject_failure_context(node, reason, violation_details)
            self._clear_generated_keys(node, dag_runtime.mode)

            try:
                dag_runtime.execute(node)
                candidates.append(json.loads(json.dumps(node.semantics)))
            except Exception as e:
                logger.error(f"Reroll candidate {i+1} failed for {node.node_id}: {e}")
                candidates.append(None)

            # Restore semantics for next candidate attempt
            if i < self.branch_count - 1:
                node.semantics = candidate_semantics

        # 3. Select best candidate (with diversity penalty for repeated structures)
        def _score_with_diversity(sem: dict, rejected_prints: list) -> float:
            base = _score_candidate(sem)
            ops = sem.get("operator_types", []) if isinstance(sem, dict) else []
            fp = hashlib.md5(str(sorted(ops)).encode("utf-8")).hexdigest()
            if fp in rejected_prints:
                base *= 0.15  # strong but non-zero — allows escape if budget exhausted
            return round(base, 4)

        valid_candidates = [
            (c, _score_with_diversity(c, self._rejected_fingerprints))
            for c in candidates if c is not None
        ]
        if not valid_candidates:
            logger.error(f"Both reroll candidates failed for {node.node_id}")
            node.epistemic.state = "REJECTED"
            node.epistemic.final_status = "reroll_execution_failed"
            return None

        best_candidate, best_score = max(valid_candidates, key=lambda x: x[1])

        # 4. Apply best candidate to node
        node.semantics = best_candidate

        # 5. Build rejected trace (DPO-compatible: has both rejected + corrected)
        rejected_trace = {
            "node_id": node.node_id,
            "rejected": rejected_snapshot,
            "corrected": best_candidate,
            "reason": reason,
            "reroll_attempt": self.reroll_count,
            "candidates_evaluated": len(valid_candidates),
            "best_score": best_score,
        }

        logger.info(f"Reroll #{self.reroll_count} completed for {node.node_id} "
                     f"({len(valid_candidates)} candidates, best_score={best_score})")
        return rejected_trace
